### ISSUE TITLE
problem about output_path

### ISSUE THREAD

**Issue by wangliewei** [bookfere/Ebook-Translator-Calibre-Plugin#1]
Traceback (most recent call last):
  File "calibre\gui2\proceed.py", line 208, in do_ask_question
  File "calibre_plugins.ebook_translator.main", line 268, in <lambda>
NameError: free variable 'output_path' referenced before assignment in enclosing scope

**Comment by bookfere** [comment]
Thank you for pointing out. It is now fixed. Please try the latest version.

**Comment by joostshao** [comment]
太慢了，这是怎么回事？有测试数据吗？
quick start guide , 都十分钟了，还没翻译完

**Comment by bookfere** [comment]
@joostshao 翻译速度和网络响应速度和设置的请求时间间隔有关。以免费的 Google 翻译为例，在正常的网络环境下，按默认设置的每个请求间隔 0~5 秒钟来算，翻译 600 段按理说不超过  50 分钟。免费的 Google 翻译 API 对请求频率有限制，有时不得不加长请求间隔，导致耗时进一步增加。
