### ISSUE TITLE
翻译完成的书输出电子书失败

### ISSUE THREAD

**Issue by mxh173** [bookfere/Ebook-Translator-Calibre-Plugin#112]
如题，日志最后报错如下

插件2.1.2 calibre 6.25

Time consuming: 0.15 minutes
翻译已完成。
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\utils\ipc\worker.py", line 150, in arbitrary_n
  File "calibre_plugins.ebook_translator.lib.conversion", line 108, in convert_book
  File "calibre\ebooks\conversion\plumber.py", line 1281, in run
  File "calibre_plugins.ebook_translator.lib.conversion", line 100, in convert
  File "calibre_plugins.ebook_translator.lib.element", line 298, in add_translations
  File "calibre_plugins.ebook_translator.lib.element", line 93, in add_translation
  File "src/lxml/etree.pyx", line 3233, in lxml.etree.XML
  File "src/lxml/parser.pxi", line 1913, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1793, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: PCDATA invalid Char value 7, line 1, column 81

![微信截图_20230828173325](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38520345/2af27072-01b2-4dcc-b5bc-90019c4c82d6)

![微信截图_20230828173344](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38520345/ae091e0d-d693-461c-8fac-835932970f88)

**Comment by bookfere** [comment]
谢谢反馈。请将电子书样本发送到邮箱 bookfere@gmail.com 以便测试。

**Comment by mxh173** [comment]
> 谢谢反馈。请将电子书样本发送到邮箱 [bookfere@gmail.com](mailto:bookfere@gmail.com) 以便测试。

已发送，辛苦了

**Comment by bookfere** [comment]
错误是百度翻译返回的译文含有特殊字符导致的。请尝试一下这个版本：

[ebook-translator-202308291214.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/12460196/ebook-translator-202308291214.zip)

**Comment by mxh173** [comment]
> 错误是百度翻译返回的译文含有特殊字符导致的。请尝试一下这个版本：
> 
> [ebook-translator-202308291214.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/12460196/ebook-translator-202308291214.zip)

这个版本没问题了，感谢大佬
