### ISSUE TITLE
RuntineError:There is no current event loop in thread 'Dummy-8'.

### ISSUE THREAD

**Issue by AnmoWu** [bookfere/Ebook-Translator-Calibre-Plugin#115]
使用高级模式，点击翻译全部/翻译指定后，会显示：

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/73103395/47022888-53ac-4eda-ac5a-744ad57327e6)

如果点击显示详细信息，Calibre则会直接闪退。

使用批量模式，会显示：

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/73103395/43d7830c-6ecd-4f79-ad9a-d8445913cb61)

详细信息如下：

```
calibre, version 5.37.0 (win32, embedded-python: True)
翻译失败: 失败: [自动探测 > Chinese (simplified)] 翻译 "So wirst du finanziell frei: 13 clevere Geldstrategien erfolgreicher Frauen"

[自动探测 > Chinese (simplified)] 翻译 "So wirst du finanziell frei: 13 clevere Geldstrategien erfolgreicher Frauen"
InputFormatPlugin: EPUB Input running
on D:\休闲\阅读\书库\Margarethe Honisch\So wirst du finanziell frei_ 13 cle (340)\So wirst du finanziell frei_ 13 - Margarethe Honisch.epub
Found HTML cover titlepage.xhtml
Parsing all content...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Creating EPUB Output...
Translating ebook content ... (this will take a while)
==============================
| Diagnosis Information
==============================
| Calibre Version: 5.37.0
| Plugin Version: v2.1.2
| Translate Engine: DeepL(Free)
| Source Language: 自动探测
| Target Language: Chinese (simplified)
| Cache Enabled: True
| Merging Length: 0
| Concurrent requests: 1
| Request Interval: 1.0
| Request Attempt: 3
| Request Timeout: 10.0
| Input Path: D:\休闲\阅读\书库\Margarethe Honisch\So wirst du finanziell frei_ 13 cle (340)\So wirst du finanziell frei_ 13 - Margarethe Honisch.epub
| Output Path: C:\Users\lenovo\AppData\Local\Temp\calibre_9_m25kak\8sq_14qe.epub
==============================
开始翻译电子书内容
==============================
全部条目：1172
Character count: 420828
Traceback (most recent call last):
File "runpy.py", line 194, in _run_module_as_main
File "runpy.py", line 87, in _run_code
File "site.py", line 82, in <module>
File "site.py", line 77, in main
File "site.py", line 49, in run_entry_point
File "calibre\utils\ipc\worker.py", line 215, in main
File "calibre\utils\ipc\worker.py", line 150, in arbitrary_n
File "calibre_plugins.ebook_translator.lib.conversion", line 108, in convert_book
File "calibre\ebooks\conversion\plumber.py", line 1281, in run
File "calibre_plugins.ebook_translator.lib.conversion", line 99, in convert
File "calibre_plugins.ebook_translator.lib.translation", line 235, in handle
File "calibre_plugins.ebook_translator.lib.async_handler", line 69, in handle
File "asyncio\runners.py", line 43, in run
File "asyncio\base_events.py", line 616, in run_until_complete
File "calibre_plugins.ebook_translator.lib.async_handler", line 58, in process_tasks
File "asyncio\queues.py", line 220, in join
File "asyncio\locks.py", line 309, in wait
RuntimeError: Task <Task pending name='Task-1' coro=<AsyncHandler.process_tasks() running at calibre_plugins.ebook_translator.lib.async_handler:58> cb=[_run_until_complete_cb() at asyncio\base_events.py:184]> got Future <Future pending> attached to a different loop
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<AsyncHandler.processing_worker() done, defined at calibre_plugins.ebook_translator.lib.async_handler:41> exception=RuntimeError("Task <Task pending name='Task-3' coro=<AsyncHandler.processing_worker() running at calibre_plugins.ebook_translator.lib.async_handler:43>> got Future <Future pending> attached to a different loop")>
Traceback (most recent call last):
File "calibre_plugins.ebook_translator.lib.async_handler", line 43, in processing_worker
File "asyncio\queues.py", line 163, in get
RuntimeError: Task <Task pending name='Task-3' coro=<AsyncHandler.processing_worker() running at calibre_plugins.ebook_translator.lib.async_handler:43>> got Future <Future pending> attached to a different loop
```

此时我的并发限制是1，将它改为100后情况不变。经过多次测试后，会显示不同的线程名错误，如Dummy-8/9/11/14等等。错误日志内容为空，不知道是python的asynio错误还是我calibre的版本问题？

**Comment by bookfere** [comment]
之前修复过一个和 asyncio 相关的错误 #110，不知是否和这个错误相关。你可以先试一下这个版本，看错误会不会重现：

[ebook-translator-202308232234.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/12420383/ebook-translator-202308232234.zip)

**Comment by bookfere** [comment]
确实是版本的问题。截图中所示版本的 Calbire 所用 Python 版本对 asyncio 的某些 API 的支持与新版本有差异，现在错误已修复，旧版本应该也没问题了。
