### ISSUE TITLE
ChatGPT engine error information

### ISSUE THREAD

**Issue by TYLERCHEN999** [bookfere/Ebook-Translator-Calibre-Plugin#138]
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 66, in translate_text
  File "calibre_plugins.ebook_translator.engines.chatgpt", line 89, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 181, in get_result
Exception: 无法解析返回的响应。原始数据：
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 171, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 400: Bad Request

**Comment by bookfere** [comment]
Thanks for your feedback. Does this issue occur when translating every paragraph or only with a specific one? Have you made any modification to the ChatGPT API endpoint in the settings?

谢谢反馈。翻译所有段落都出现这个问题，还是翻译某个段落时出现这个问题？是否在设置中改动了 ChatGPT 的 API 端点？

**Comment by TYLERCHEN999** [comment]
我现在完全无法正常使用这个插件，API端点没有改动过，也卸载重装这个插件好几次，之前用chatgpt（azure）和openai都正常，测试翻译时就显示上面的信息，现在连DeepL和其它引擎似乎也都不行，不知道啥原因，对梯子设置有啥要求吗？
