### ISSUE TITLE
翻译完成后，导出epub错误

### ISSUE THREAD

**Issue by Benson1997** [bookfere/Ebook-Translator-Calibre-Plugin#154]
如题：

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/30276eb5-8524-40ad-ba44-d50ed12d4243)

翻译已完成。
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\utils\ipc\worker.py", line 150, in arbitrary_n
  File "calibre_plugins.ebook_translator.lib.conversion", line 112, in convert_book
  File "calibre\ebooks\conversion\plumber.py", line 1281, in run
  File "calibre_plugins.ebook_translator.lib.conversion", line 104, in convert
  File "calibre_plugins.ebook_translator.lib.element", line 309, in add_translations
  File "calibre_plugins.ebook_translator.lib.element", line 134, in add_translation
  File "src/lxml/etree.pyx", line 3233, in lxml.etree.XML
  File "src/lxml/parser.pxi", line 1913, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1793, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: PCDATA invalid Char value 8, line 1, column 54

**Comment by bookfere** [comment]
看起来是特定内容的问题，可以把发一份电子书样本到 bookfere@gmail.com，以便测试。

**Comment by Benson1997** [comment]
电子书样本已发送至  [bookfere@gmail.com] ，辛苦啦~

**Comment by bookfere** [comment]
#189
