### ISSUE TITLE
ChatGPT translator engine error

### ISSUE THREAD

**Issue by huronhorn** [bookfere/Ebook-Translator-Calibre-Plugin#156]
i tried latest rolling release for ebook translator, but when i try to translate a book using chatgpt engine it show error:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 66, in translate_text
  File "calibre_plugins.ebook_translator.engines.chatgpt", line 91, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 196, in get_result
Exception: Can not parse returned response. Raw data: 

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 186, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 429: Too Many Requests

do i need chatgpt premium account? thanks

**Comment by jcmefra** [comment]
Same issue.

**Comment by bookfere** [comment]
Your OpenAI account has free tier rate limits of 3 requests per minute. To ensure you stay within these limits, please be mindful of your request frequency. If you need more requests, consider upgrading to a premium plan.
