### ISSUE TITLE
使用自己的ChatGPT api，SSL证书验证失败

### ISSUE THREAD

**Issue by Heithon** [bookfere/Ebook-Translator-Calibre-Plugin#159]
这个api在别处都可以正常工作，但是在插件里面无法解析返回值，显示证书验证失败了，希望能协助解决，感谢🙏

报错如下：

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 66, in translate_text
  File "calibre_plugins.ebook_translator.engines.chatgpt", line 92, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 195, in get_result
Exception: 无法解析返回的响应。原始数据：
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 185, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 287, in _mech_open
  File "mechanize\_opener.py", line 193, in open
  File "mechanize\_urllib2_fork.py", line 425, in _open
  File "mechanize\_urllib2_fork.py", line 414, in _call_chain
  File "mechanize\_urllib2_fork.py", line 1283, in https_open
  File "mechanize\_urllib2_fork.py", line 1240, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

![Uploading image.png…]()

**Comment by bookfere** [comment]
图片未上传成功。你所说的“自己的ChatGPT api”具体指的是什么，是 OpenAI 官方提供的 API 吗？

**Comment by Heithon** [comment]
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/85172139/0e316c16-ae5e-41a3-a19f-8211d809313e)

我使用的是转发接口，用的自己的端口地址，在其他应用上工作正常，比如chatbox还有一些浏览器插件都是正常的。Calibre中测试翻译显示如上，证书已过期。

**Comment by bookfere** [comment]
现在不再检查证书了，可以访问 https://translator.bookfere.com 点击【Rolling Release】下载刚刚更新的版本再试试看。
