### ISSUE TITLE
Error translate with DeepL (free)

### ISSUE THREAD

**Issue by pyromaker** [bookfere/Ebook-Translator-Calibre-Plugin#166]
Hello guys,
First thing I want to say is thank you very much for creating this plugin!

The error I am expieriencig is this one bellow.

I am trying to translate a book (Harry Potter and the chamber of secrets) and I get this error.

The translate engine I selected is DeepL (Free) and the engine API error kinda confuses me

```
Original: Pottermore.com
-----------------------------------
Error: Failed to retrieve data from translate engine API.
Can not parse returned response. Raw data:
Traceback (most recent call last):
File "calibre_plugins.ebook_translator.engines.base ", line 185, in get_result
File "mechanize\_mechanize.py", line 257, in open
File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals >.httperror_seek_wrapper: HTTP Error 429:
==============================
Original: Contents
-----------------------------------
Error: Failed to retrieve data from translate engine API.
Can not parse returned response. Raw data:
Traceback (most recent call last):
File "calibre_plugins.ebook_translator.engines.base ", line 185, in get_result
File "mechanize\_mechanize.py", line 257, in open
File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals >.httperror_seek_wrapper: HTTP Error 429:
```

With the Google translate, everything works fine but I trust more DeepL translation, I think it's much more better than google.

**Comment by kamaqnkatyqn** [comment]
This is just an idea:

I suggest implementing the glossary function for the DeepL translation provider (using the Free API).

The other glossary function, which is already implemented in the plugin, is not bad, but I realized that grammar errors are introduced when I use it. With DeepL's native glossary function, there wouldn't be grammar errors.

**Comment by pyromaker** [comment]
I tried with DeepL free with API.
The translation completed untill 99%.

In the end I got this error.

```
Error: Failed to retrieve data from translate engine API.
Can not parse returned response. Raw data: 
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 185, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 456:
==============================
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\utils\ipc\worker.py", line 150, in arbitrary_n
  File "calibre_plugins.ebook_translator.lib.conversion", line 112, in convert_book
  File "calibre\ebooks\conversion\plumber.py", line 1281, in run
  File "calibre_plugins.ebook_translator.lib.conversion", line 103, in convert
  File "calibre_plugins.ebook_translator.lib.translation", line 247, in handle
Exception: Translation failed.
```

**Comment by bookfere** [comment]
I can identify two issues from the information you provided:

* __HTTP Error 429__: Your request frequency exceeds the limits of DeepL. [via](https://support.deepl.com/hc/en-us/articles/360020710619-Error-code-429)
* __HTTP Error 456__: The character count of a paragraph exceeds the limits of DeepL. [via](https://support.deepl.com/hc/en-us/articles/360020681140-Error-code-456)

For the first issue, I recommend that you set an appropriate request frequency for DeepL in the plugin settings. For the second issue, we will continue to work on finding a solution.

**Comment by bookfere** [comment]
The performance of DeepL (Free) isn't as consistent as expected, so you might need to tweak the request settings to make it function smoothly. We suggest adjusting the default "Interval" setting of 1 second to an appropriate value that ensures continuous operation.
