### ISSUE TITLE
翻译-提电子书内容异常-有的epub不支持翻译吗 ?

### ISSUE THREAD

**Issue by gaocrownclown** [bookfere/Ebook-Translator-Calibre-Plugin#169]
calibre, version 6.29.0
错误： 未处理的异常: <b>TypeError</b>:find() takes no keyword arguments

calibre 6.29 Portable embedded-python: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.10.1
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: Ebook Translator (2, 2, 0)
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.advanced", line 90, in prepare_ebook_data
  File "calibre_plugins.ebook_translator.lib.conversion", line 35, in extract_ebook_elements
  File "calibre\ebooks\conversion\plumber.py", line 1281, in run
  File "calibre_plugins.ebook_translator.lib.conversion", line 33, in convert
  File "calibre_plugins.ebook_translator.lib.element", line 383, in get_page_elements
  File "calibre_plugins.ebook_translator.lib.element", line 204, in get_elements
TypeError: find() takes no keyword arguments

**Comment by gaocrownclown** [comment]
The eBook is:

**Comment by gaocrownclown** [comment]
电子书是: https://zh.z-library.se/book/5294714/20a4b2

**Comment by bookfere** [comment]
错误已修复，下载安装 [Rolling Release](https://translator.bookfere.com) 再试试看。
