### ISSUE TITLE
[bug]原因不明的翻译任务冻结问题

### ISSUE THREAD

**Issue by WeeAris** [bookfere/Ebook-Translator-Calibre-Plugin#186]
截至目前在[该快照版本](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/commit/9d45c3d7d8eb689e84fa8b4d7591c15eb59c5da7)和前1提交版本下多次遇到批量任务时个别任务冻结问题，具体表现为任务进度长时间无更新且任务不会超时退出直到手动终止，翻译日志界面也无任何错误和警告信息，最长一次冻结了一个半小时也没停止（超时设置5s左右，重试次数2，最大错误总数5，并发设置2，开启了合并翻译及手动设置代理），另外高级翻译界面偶尔也会出现冻结现象，且手动停止一直显示停止中。

注：由于长时间未使用该插件，故之前版本情况不明，calibre版本7.0~7.1，系统Windows 10 LTSC2021

**Comment by bookfere** [comment]
貌似是和 #182 一样的问题。是个别电子书有这个问题吗？如果是的话可以把样本发到邮箱以便测试。

**Comment by WeeAris** [comment]
> 貌似是和 #182 一样的问题。是个别电子书有这个问题吗？如果是的话可以把样本发到邮箱以便测试。

没有发现和文件的关联，但意外发现代理不稳定的时候有可能会导致这个问题，不过还不确定。

**Comment by bookfere** [comment]
这个问题的原因应该是插件不断重试出错的请求导致的。由于之前插件没有记录重试期间的错误信息，所以就像卡住一样。提交 b1869db311a6a9c997f2a5a2a10820a7f01b75e7 修复了这个问题，应该就可以根据日志排查问题了。

**Comment by WeeAris** [comment]
> 这个问题的原因应该是插件不断重试出错的请求导致的。由于之前插件没有记录重试期间的错误信息，所以就像卡住一样。提交 [b1869db](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/commit/b1869db311a6a9c997f2a5a2a10820a7f01b75e7) 修复了这个问题，应该就可以根据日志排查问题了。
感谢，现在可以看到错误日志了。任务冻结前的日志如下：
```
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
状态：失败 1 次 / 等待 5 秒
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
错误信息：无法解析返回的响应。原始数据：

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 204, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 287, in _mech_open
  File "mechanize\_opener.py", line 193, in open
  File "mechanize\_urllib2_fork.py", line 425, in _open
  File "mechanize\_urllib2_fork.py", line 414, in _call_chain
  File "mechanize\_urllib2_fork.py", line 1283, in https_open
  File "mechanize\_urllib2_fork.py", line 1240, in do_open
urllib.error.URLError: <urlopen error The read operation timed out>
```
然后就一直这样了，也没有发现它进行重试的迹象，目前发现的例子日志的错误类型都是完全一样的，在第一次失败之后就没动静了。而如果是其他错误，例如网络错误，并不会冻住。
