### ISSUE TITLE
[BUG] Can't translate any epub, pdf. 

### ISSUE THREAD

**Issue by orcbolg3612** [bookfere/Ebook-Translator-Calibre-Plugin#198]
```
calibre, version 6.28.1 (linux, embedded-python: False)
Translation job failed: Failed: [English > Vietnamese] Translating "The Alter Ego Effect"

[English > Vietnamese] Translating "The Alter Ego Effect"
InputFormatPlugin: EPUB Input running
on /home/orcbolg/Calibre Library/Todd Herman/The Alter Ego Effect (5)/The Alter Ego Effect - Todd Herman.epub
Found HTML cover OEBPS/text/9780062838674_Cover.xhtml
Parsing all content...
Merging user specified metadata...
Detecting structure...
	Detected chapter: Chapter 1
	Detected chapter: Chapter 2
	Detected chapter: Chapter 3
	Detected chapter: Chapter 4
	Detected chapter: Chapter 5
	Detected chapter: Chapter 6
	Detected chapter: Chapter 7
	Detected chapter: Chapter 8
	Detected chapter: Chapter 9
	Detected chapter: Chapter 10
	Detected chapter: Chapter 11
	Detected chapter: Chapter 12
	Detected chapter: Chapter 13
	Detected chapter: Chapter 14
	Detected chapter: Chapter 15
	Detected chapter: Chapter 16
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Trimming 'OEBPS/9780062838674_toc.ncx' from manifest
Creating EPUB Output...
Translating ebook content ... (this will take a while)
==============================
| Diagnosis Information
==============================
| Calibre Version: 6.28.1
| Plugin Version: v2.2.0
| Translation Engine: Google(Free)
| Source Language: English
| Target Language: Vietnamese
| Cache Enabled: True
| Merging Length: 0
| Concurrent requests: 0
| Request Interval: 0.0
| Request Attempt: 3
| Request Timeout: 10.0
| Input Path: /home/orcbolg/Calibre Library/Todd Herman/The Alter Ego Effect (5)/The Alter Ego Effect - Todd Herman.epub
| Output Path: /tmp/calibre_6.28.1_tmp_vmnnz8_u/f3c4t155.epub
==============================
Start to translate ebook content
==============================
Total items: 2856
Character count: 423824
==============================
Original: Chapter 1: What’s Your Phone Booth Moment?
-----------------------------------
Error: Failed to retrieve data from translate engine API.
Can not parse returned response. Raw data: 
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 185, in get_result
    br.open(request)
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_opener.py", line 193, in open
    response = urlopen(self, req, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 425, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 414, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1283, in https_open
    return self.do_open(conn_factory, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1196, in do_open
    h = http_class(host_port, timeout=req.timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HTTPSConnection.__init__() got an unexpected keyword argument 'key_file'
==============================
Original: Chapter 9: Choosing Your Extraordinary World
-----------------------------------
Error: Failed to retrieve data from translate engine API.
Can not parse returned response. Raw data: 
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 185, in get_result
    br.open(request)
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_opener.py", line 193, in open
    response = urlopen(self, req, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 425, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 414, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1283, in https_open
    return self.do_open(conn_factory, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1196, in do_open
    h = http_class(host_port, timeout=req.timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HTTPSConnection.__init__() got an unexpected keyword argument 'key_file'
==============================
Original: Chapter 11: Defining Your Superpowers and Crafting the Name
-----------------------------------
Error: Failed to retrieve data from translate engine API.
Can not parse returned response. Raw data: 
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 185, in get_result
    br.open(request)
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_opener.py", line 193, in open
    response = urlopen(self, req, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 425, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 414, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1283, in https_open
    return self.do_open(conn_factory, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1196, in do_open
    h = http_class(host_port, timeout=req.timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HTTPSConnection.__init__() got an unexpected keyword argument 'key_file'
==============================
Original: Chapter 6: The Hidden Forces of the Enemy
-----------------------------------
Error: Failed to retrieve data from translate engine API.
Can not parse returned response. Raw data: 
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 185, in get_result
    br.open(request)
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_opener.py", line 193, in open
    response = urlopen(self, req, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 425, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 414, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1283, in https_open
    return self.do_open(conn_factory, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1196, in do_open
    h = http_class(host_port, timeout=req.timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HTTPSConnection.__init__() got an unexpected keyword argument 'key_file'
==============================
Original: Chapter 5: Finding Your Moments of Impact
-----------------------------------
Error: Failed to retrieve data from translate engine API.
Can not parse returned response. Raw data: 
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 185, in get_result
    br.open(request)
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_opener.py", line 193, in open
    response = urlopen(self, req, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 425, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 414, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1283, in https_open
    return self.do_open(conn_factory, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1196, in do_open
    h = http_class(host_port, timeout=req.timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HTTPSConnection.__init__() got an unexpected keyword argument 'key_file'
==============================
Original: Title Page
-----------------------------------
Error: Failed to retrieve data from translate engine API.
Can not parse returned response. Raw data: 
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 185, in get_result
    br.open(request)
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_opener.py", line 193, in open
    response = urlopen(self, req, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 425, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 414, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1283, in https_open
    return self.do_open(conn_factory, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1196, in do_open
    h = http_class(host_port, timeout=req.timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HTTPSConnection.__init__() got an unexpected keyword argument 'key_file'
==============================
Original: Dedication
-----------------------------------
Error: Failed to retrieve data from translate engine API.
Can not parse returned response. Raw data: 
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 185, in get_result
    br.open(request)
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_opener.py", line 193, in open
    response = urlopen(self, req, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 425, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 414, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1283, in https_open
    return self.do_open(conn_factory, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1196, in do_open
    h = http_class(host_port, timeout=req.timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HTTPSConnection.__init__() got an unexpected keyword argument 'key_file'
==============================
Original: Chapter 8: The Power of Your Story
-----------------------------------
Error: Failed to retrieve data from translate engine API.
Can not parse returned response. Raw data: 
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 185, in get_result
    br.open(request)
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_opener.py", line 193, in open
    response = urlopen(self, req, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 425, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 414, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1283, in https_open
    return self.do_open(conn_factory, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1196, in do_open
    h = http_class(host_port, timeout=req.timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HTTPSConnection.__init__() got an unexpected keyword argument 'key_file'
==============================
Original: Contents
-----------------------------------
Error: Failed to retrieve data from translate engine API.
Can not parse returned response. Raw data: 
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 185, in get_result
    br.open(request)
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_opener.py", line 193, in open
    response = urlopen(self, req, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 425, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 414, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1283, in https_open
    return self.do_open(conn_factory, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1196, in do_open
    h = http_class(host_port, timeout=req.timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HTTPSConnection.__init__() got an unexpected keyword argument 'key_file'
==============================
Original: Chapter 2: The Origin of Alter Egos
-----------------------------------
Error: Failed to retrieve data from translate engine API.
Can not parse returned response. Raw data: 
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 185, in get_result
    br.open(request)
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_opener.py", line 193, in open
    response = urlopen(self, req, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 425, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 414, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1283, in https_open
    return self.do_open(conn_factory, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1196, in do_open
    h = http_class(host_port, timeout=req.timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HTTPSConnection.__init__() got an unexpected keyword argument 'key_file'
==============================
Traceback (most recent call last):
  File "/usr/bin/calibre-parallel", line 21, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib64/calibre/calibre/utils/ipc/worker.py", line 214, in main
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/calibre/calibre/utils/ipc/worker.py", line 149, in arbitrary_n
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.ebook_translator.lib.conversion", line 112, in convert_book
  File "/usr/lib64/calibre/calibre/ebooks/conversion/plumber.py", line 1281, in run
    self.output_plugin.convert(self.oeb, self.output, self.input_plugin,
  File "calibre_plugins.ebook_translator.lib.conversion", line 103, in convert
  File "calibre_plugins.ebook_translator.lib.translation", line 247, in handle
Exception: Translation failed.
```

**Comment by orcbolg3612** [comment]
This error appear on all translator engine.

**Comment by bookfere** [comment]
The problem is related to an incorrect Calibre environment. It's likely that you installed a Calibre version without embedded Python, which can cause many problems. I suggest referring to [Calibre's instruction](https://calibre-ebook.com/download_linux) for installation to ensure that it includes embedded Python.
