### ISSUE TITLE
gpt3.5 报错。以前能用，最近一直抽风

### ISSUE THREAD

**Issue by tongcuyu** [bookfere/Ebook-Translator-Calibre-Plugin#202]
错误信息：无法解析返回的响应。原始数据：

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 204, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 429: Too Many Requests

{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

**Comment by tongcuyu** [comment]
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 66, in translate_text
  File "calibre_plugins.ebook_translator.engines.chatgpt", line 94, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 217, in get_result
Exception: 无法解析返回的响应。原始数据：

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 204, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 287, in _mech_open
  File "mechanize\_opener.py", line 193, in open
  File "mechanize\_urllib2_fork.py", line 425, in _open
  File "mechanize\_urllib2_fork.py", line 414, in _call_chain
  File "mechanize\_urllib2_fork.py", line 1283, in https_open
  File "mechanize\_urllib2_fork.py", line 1240, in do_open
urllib.error.URLError: <urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)>

**Comment by bookfere** [comment]
从错误信息看，这两个错误都和插件没有关联。第一个错误显示额度不足，建议检查账户是否还有充足额度。第二个错误是网络问题，建议尝试更换网络或代理。
