### ISSUE TITLE
ISSUE : Gemini Pro 

### ISSUE THREAD

**Issue by delta-whiplash** [bookfere/Ebook-Translator-Calibre-Plugin#211]
hello am trying to translate a book with gemini pro but I have few error : 
```
Status: Failed 1 times / Sleeping for 5 seconds
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
Erreur: Ne peux analyser la réponse retournée. Data non-traité: 

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 204, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 287, in _mech_open
  File "mechanize\_opener.py", line 193, in open
  File "mechanize\_urllib2_fork.py", line 425, in _open
  File "mechanize\_urllib2_fork.py", line 414, in _call_chain
  File "mechanize\_urllib2_fork.py", line 1283, in https_open
  File "mechanize\_urllib2_fork.py", line 1240, in do_open
urllib.error.URLError: <urlopen error The read operation timed out>
```

be free to ask me more details if you need them

**Comment by bookfere** [comment]
According to the error, the engine cannot even provide a response. It's related to a network issue. I suggest you check if your network is available for the [Gemini API](https://ai.google.dev/tutorials/rest_quickstart).

**Comment by delta-whiplash** [comment]
Can I use Gemini pro from vertex ai ?
