### ISSUE TITLE
Error：部分epub文件提示Failed to initialize plugin:错误，完全没有开始翻译。

### ISSUE THREAD

**Issue by Benson1997** [bookfere/Ebook-Translator-Calibre-Plugin#212]
老大您好，请问：批量翻译多个epub时，有些epub文件会提示初始化插件错误，完全没有开始翻译。

错误：Failed to initialize plugin: 'D:\\Programs\\Calibre_Portable\\Calibre Settings\\plugins\\DeDRM.zip'

![00000](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/2131ebbc-87bd-4a5e-8e7a-221644fb44bf)

报错文件和缓存文件附上：
[bug-初始化错误（epub+缓存）.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/14381308/bug-.epub%2B.zip)

`[English > 中文] 翻译 "Getting (More Of) What You Want _ How the Secrets of Economics and Psychology Can Help You Negotiate Anything, in Business and in Life (9780465040636)"
Failed to initialize plugin: 'D:\\Programs\\Calibre_Portable\\Calibre Settings\\plugins\\DeDRM.zip'
InputFormatPlugin: EPUB Input running
on D:\Programs\Calibre_Portable\Calibre Library\Neale, Margaret A.; Lys, Thomas Z_\Getting (More Of) What You Want _ H (605)\Getting (More Of) What You Want - Neale, Margaret A.; Lys, Thomas.epub
Found HTML cover titlepage.xhtml
Parsing all content...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 11.99998pt
Removing fake margins...
Removing page margins specified in the Adobe page template
Cleaning up manifest...
Trimming unused files from manifest...
Creating EPUB Output...
Translating ebook content ... (this will take a while)
══════════════════════════════════════
| Diagnosis Information
══════════════════════════════════════
| Calibre Version: 6.27.0
| Plugin Version: v2.2.0
| Translation Engine: AI GUO GUO
| Source Language: English
| Target Language: 中文
| Cache Enabled: True
| Merging Length: 0
| Concurrent requests: 300
| Request Interval: 0.0
| Request Attempt: 5
| Request Timeout: 600.0
| Input Path: D:\Programs\Calibre_Portable\Calibre Library\Neale, Margaret A.; Lys, Thomas Z_\Getting (More Of) What You Want _ H (605)\Getting (More Of) What You Want - Neale, Margaret A.; Lys, Thomas.epub
| Output Path: H:/Getting (More Of) What You Want _ How the Secrets of Economics and Psychology Can Help You Negotiate Anything, in Business and in Life (9780465040636) [中文].epub
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\utils\ipc\worker.py", line 150, in arbitrary_n
  File "calibre_plugins.ebook_translator.lib.conversion", line 101, in convert_item
  File "calibre_plugins.ebook_translator.lib.conversion", line 135, in convert_book
  File "calibre\ebooks\conversion\plumber.py", line 1281, in run
  File "calibre_plugins.ebook_translator.lib.conversion", line 121, in convert
  File "calibre_plugins.ebook_translator.lib.element", line 462, in get_page_elements
  File "calibre_plugins.ebook_translator.lib.element", line 232, in get_elements
  File "calibre_plugins.ebook_translator.lib.element", line 243, in extract_elements
AttributeError: 'NoneType' object has no attribute 'findall'
`

**Comment by bookfere** [comment]
谢谢反馈。错误已在提交 dbf8cf194c5a1a37067605aa4c2e1843428b500b 中修复。
