### ISSUE TITLE
对缓存sqlite文件内的翻译文本进行修改后，导出时提示错误

### ISSUE THREAD

**Issue by GoTop** [bookfere/Ebook-Translator-Calibre-Plugin#227]
为用的是rolling release版，但是翻译时使用的插件版本和现在的插件版本不同

我读取缓存的sqlite数据库，对里面的翻译文本进行了修改（处理一些原文和翻译的分段数量不相同的问题等）。因为看到每个原文最后都有两个\n\n，我还在每个翻译文本最后加入了两个换行符\n\n

将sqlite文件复制到插件的缓存目录后，读取显示正常，没有黄色标识提示，但是点击“输出”后，提示下面的错误。

缓存文件： https://transfer.pcloud.com/download.html?code=5Z8PbF0ZaOjuW6aEJvbZB9d3ZkwJDx464cHy8hLBKSVGrGuLK9ogV

提示出错误log：https://transfer.pcloud.com/download.html?code=5ZvPbF0ZaOjuW6aEJvbZB9d3Zi33j7aa4EKzbG2xzXlkiYfVfdx1V

这是错误log的大概内容：
```
[English > 中文] 翻译 "Inside the Black Box_ A Simple Guide to Quantitative and High-Frequency Trading"
InputFormatPlugin: EPUB Input running
on /Users/mac/Calibre Lib/Rishi K. Narang/Inside the Black Box_ A Simple Guide to Quantitative and High-Frequency Trading (250)/Inside the Black Box_ A Simple Guide to Qu - Rishi K. Narang.epub
Found HTML cover titlepage.xhtml
Parsing all content...
Referenced file 'OEBPS/WileySD_templateV4.4.css' not found
Spine-referenced file 'OEBPS/9781118416990_epub_cov.htm' not in spine
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Stylesheet 'OEBPS/WileySD_templateV4.4.css' referenced by file 'OEBPS/9781118416990_epub_cov.htm' not in manifest
Source base font size is 12.00001pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Creating EPUB Output...
Translating ebook content ... (this will take a while)
══════════════════════════════════════
| Diagnosis Information
══════════════════════════════════════
| Calibre Version: 7.6.0
| Plugin Version: v2.2.0
| Translation Engine: coze-discord-proxy
| Source Language: English
| Target Language: 中文
| Cache Enabled: True
| Merging Length: 1000
| Concurrent requests: 4
| Request Interval: 5.0
| Request Attempt: 1
| Request Timeout: 600.0
| Input Path: /Users/mac/Calibre Lib/Rishi K. Narang/Inside the Black Box_ A Simple Guide to Quantitative and High-Frequency Trading (250)/Inside the Black Box_ A Simple Guide to Qu - Rishi K. Narang.epub
| Output Path: /var/folders/db/j3wrt9gd619c809zk5pj_2fc0000gn/C/calibre_7.6.0_tmp_xldahxe1/lour5_79.epub
══════════════════════════════════════
开始翻译电子书内容
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
全部条目：869
字符总数：757590
══════════════════════════════════════
原文：Cover

Additional Praise for Inside the Black Box

Series

Title Page

Copyright

Dedication

Preface to the Second Edition

Acknowledgments

Part One: The Quant Universe

Chapter 1: Why Does Quant Trading Matter?

THE BENEFIT OF DEEP THOUGHT

THE MEASUREMENT AND MISMEASUREMENT OF RISK

DISCIPLINED IMPLEMENTATION

SUMMARY

NOTES

Chapter 2: An Introduction to Quantitative Trading

WHAT IS A QUANT?

WHAT IS THE TYPICAL STRUCTURE OF A QUANTITATIVE TRADING SYSTEM?

SUMMARY

NOTES

Part Two: Inside the Black Box

Chapter 3: Alpha Models: How Quants Make Money

TYPES OF ALPHA MODELS: THEORY-DRIVEN AND DATA-DRIVEN

THEORY-DRIVEN ALPHA MODELS

DATA-DRIVEN ALPHA MODELS

IMPLEMENTING THE STRATEGIES

BLENDING ALPHA MODELS

SUMMARY

NOTES

Chapter 4: Risk Models

LIMITING THE AMOUNT OF RISK

LIMITING THE TYPES OF RISK

SUMMARY

NOTES

Chapter 5: Transaction Cost Models

DEFINING TRANSACTION COSTS

TYPES OF TRANSACTION COST MODELS

SUMMARY

NOTE

Chapter 6: Portfolio Construction Models
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
译文（缓存）：封面

《黑匣子内部》获得的额外好评

系列丛书

书名页

版权信息

致谢词

为第二版所作的序

感谢名单

第一部分：量化交易的宇宙

第1章：量化交易为何至关重要？

深入思考的好处

风险的准确衡量与误判

严格执行

小结

脚注

第2章：引领你进入量化交易

量化分析师是什么？

一个量化交易系统典型的结构又是怎样的？

小结

脚注

第二部分：揭开黑匣子

第3章：阿尔法模型：量化如何赚钱

阿尔法模型的种类：基于理论与基于数据的模型

基于理论的阿尔法模型

基于数据的阿尔法模型

策略实施

混合不同的阿尔法模型

小结

脚注

第4章：风险模型

如何控制风险的总量

如何控制风险的种类

小结

脚注

第5章：交易成本模型

交易成本的定义

不同类型的交易成本模型

小结

脚注

第6章：组合建模
══════════════════════════════════════
{{这些删减了很多内容}}
══════════════════════════════════════
原文：SUMMARY

NOTES

Chapter 12: Evaluating Quants and Quant Strategies

GATHERING INFORMATION

EVALUATING A QUANTITATIVE TRADING STRATEGY

EVALUATING THE ACUMEN OF QUANTITATIVE TRADERS

THE EDGE

EVALUATING INTEGRITY

HOW QUANTS FIT INTO A PORTFOLIO

SUMMARY

NOTE

Part Four: High-Speed and High-Frequency Trading

Chapter 13: An Introduction to High-Speed and High-Frequency Trading*

NOTES

Chapter 14: High-Speed Trading

WHY SPEED MATTERS

SOURCES OF LATENCY

SUMMARY

NOTES

Chapter 15: High-Frequency Trading

CONTRACTUAL MARKET MAKING

NONCONTRACTUAL MARKET MAKING

ARBITRAGE

FAST ALPHA

HFT RISK MANAGEMENT AND PORTFOLIO CONSTRUCTION

SUMMARY

NOTE

Chapter 16: Controversy Regarding High-Frequency Trading

DOES HFT CREATE UNFAIR COMPETITION?

DOES HFT LEAD TO FRONT-RUNNING OR MARKET MANIPULATION?

DOES HFT LEAD TO GREATER VOLATILITY OR STRUCTURAL INSTABILITY?

DOES HFT LACK SOCIAL VALUE?

REGULATORY CONSIDERATIONS

SUMMARY

NOTES

Chapter 17: Looking to the Future of Quant Trading
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
译文（缓存）：摘要

附注

第 12 章：对量化投资者和策略的评估

收集信息

对量化交易策略的评估

评价量化交易者的洞察力

优势

诚信度的评估

量化投资者在投资组合中的角色

摘要

附注

第四部分：高速和高频交易

第 13 章：高速和高频交易简介 *

附注

第 14 章：高速交易

速度的重要性

延迟的来源

摘要

附注

第 15 章：高频交易

合约市场制造

非合约市场制造

套利

迅速的 Alpha（Alpha）

HFT 风险管理和投资组合构建

摘要

附注

第 16 章：高频交易的争论

高频交易是否产生了不公平的竞争？

高频交易会导致提前交易或市场操控吗？

高频交易会增加更大的波动性或结构不稳定性吗？

高频交易缺乏社会价值吗？

监管的考虑因素

摘要

附注

第 17 章：展望量化交易的未来
══════════════════════════════════════
原文：About the Author

Index
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
译文（缓存）：关于本书作者

目录
══════════════════════════════════════
Time consuming: 0.0 minutes
翻译已完成。
Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 41, in <module>
  File "site.py", line 37, in main
  File "calibre/utils/ipc/worker.py", line 215, in main
  File "calibre/utils/ipc/worker.py", line 150, in arbitrary_n
  File "calibre_plugins.ebook_translator.lib.conversion", line 101, in convert_item
  File "calibre_plugins.ebook_translator.lib.conversion", line 135, in convert_book
  File "calibre/ebooks/conversion/plumber.py", line 1281, in run
  File "calibre_plugins.ebook_translator.lib.conversion", line 127, in convert
  File "calibre_plugins.ebook_translator.lib.element", line 422, in add_translations
  File "calibre_plugins.ebook_translator.lib.element", line 416, in align_paragraph
IndexError: pop index out of range
```

**Comment by bookfere** [comment]
这是你在译文后添加换行符导致的。缓存是由程序管理的，不建议手动修改。如果想要修改软件行为，建议修改程序而不是缓存。

**Comment by GoTop** [comment]
> 这是你在译文后添加换行符导致的。缓存是由程序管理的，不建议手动修改。如果想要修改软件行为，建议修改程序而不是缓存。

因为我想通过python处理返回的翻译文本，所以需要读取缓存的sqlite文件，对翻译文本进行一些处理。

我没学过Calibre的插件运行机制，不太懂怎么修改程序呢，感觉学习曲线应该挺高。但是从sqlite中读取文本来修改倒是挺容易的，但是最近的版本里有分段匹配检测，我不太了解这个匹配的原则。

我在sqlite里看到每个原文的段落之间是两个换行符，而我通过openai获取的翻译的文本的段落之间只有一个换行符，是否插件就是这么设计的？我需要将翻译中的一个换行符替换成两个换行符吗？

我还看到每段原文的最后都有两个\n\n，但是每段翻译文本的最后都没有换行符，这里需要手动添加两个换行符\n\n吗？

**Comment by bookfere** [comment]
原文添加的两个换行符是用来识别新分隔方式的（为了区别之前用 ID 分割内容的方式），译文不需要有换行符。

如果你想要修改有关合并段落的逻辑，可以查看 `lib/element.py` 这个模块中的 `ElementHandlerMerge` 这个类，里面的 `align_paragraph` 方法包含了对齐行的逻辑。

**Comment by GoTop** [comment]
我刚才将插件ebook-translator_20240304213912版删除，重新安装ebook-translator_20231218135354版，就可以成功导出翻译的书籍了

我翻译的这本书，之前是使用ebook-translator_20231218135354版进行翻译的，然后最近我才安装了ebook-translator_20240304213912版，可能是这两个版本倒出时对合并段落进行的不同处理导致的

有一个奇怪的问题，我使用ebook-translator_20240304213912版对这本书进行合并翻译，翻译页面也只显示全书只有前面三段，和我使用这个版本倒出双语版时，提示错误的地方一样。

我把原始书籍epub上传到这里了
https://u.pcloud.link/publink/show?code=XZT6bF0Ztc4p8EUjPLuitYbQzD10Hf2KeMJk

**Comment by bookfere** [comment]
新版本没有办法完全兼容老版本，因为新版对原文的处理也有改变，这可能会导致新版本无法识别老版本缓存中的原文。

P.S. GitHub 可以直接上传文件，并且更方便下载，不需要外链。

**Comment by GoTop** [comment]
> 新版本没有办法完全兼容老版本，因为新版对原文的处理也有改变，这可能会导致新版本无法识别老版本缓存中的原文。
> 
> P.S. GitHub 可以直接上传文档，并且更方便下载，不需要外链。

原来是github支持上传除了图片之外的文件，只要压缩成zip就可以了，我也是刚刚知道，多谢提醒

**Comment by GoTop** [comment]
> 原文添加的两个换行符是用来识别新分隔方式的（为了区别之前用 ID 分割内容的方式），译文不需要有换行符。
> 
> 如果你想要修改有关合并段落的逻辑，可以查看 `lib/element.py` 这个模块中的 `ElementHandlerMerge` 这个类，里面的 `align_paragraph` 方法包含了对齐行的逻辑。

我测试了一下，原文中如果是有多段的，译文对应的多段之间必须也是使用双换行 \n\n 来分隔才行，否则最新版插件会提示段落数不对，无法“输出”双语版
