### ISSUE TITLE
[错误报告] 设置输出路径后，文件输出失败

### ISSUE THREAD

**Issue by Baiyssy** [bookfere/Ebook-Translator-Calibre-Plugin#242]
**基础信息**
翻译正常，输出报错。我尝试了两台电脑和各种输出格式，包括epub、mobi、docx、txt，都报错。
后来发现设置了输出路径就报错，设置为书库就没问题。

* 操作系统: **Windows 11 x64**
* Calibre 版本: **7.7.0**
* 插件来源: **安装自 Calibre**

**描述错误**
```
calibre, version 7.7.0
错误： 未处理的异常: <b>OSError</b>:[WinError 87] 参数错误。: 'D:/Downloads\\A Novel [Chinese (Simplified)].epub' -&gt; 'D:/Downloads\\A Novel.epub'

calibre 7.7  embedded-python: True
Windows-10-10.0.22635-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22635')
Python 3.11.5
Windows: ('10', '10.0.22635', 'SP0', 'Multiprocessor Free')
Interface language: zh_CN
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: Ebook Translator (2, 3, 2)
Traceback (most recent call last):
  File "calibre\gui2\__init__.py", line 756, in dispatch
  File "calibre_plugins.ebook_translator.lib.conversion", line 283, in translate_done
OSError: [WinError 87] 参数错误。: 'D:/Downloads\\A Novel [Chinese (Simplified)].epub' -> 'D:/Downloads\\A Novel.epub'
```

**Comment by bookfere** [comment]
手头没有 Windows 11，用 Windows 7 测试没能重现错误。你设置的路径是通过按钮选择的还是手动输入的？因为从错误信息看到路径出现了分隔符不一致的情况。

**Comment by Baiyssy** [comment]
按钮选择的。
之前用2.2版本输出正常，2.3只输出了一个0字节的文件。
刚试了一下，手动输入D:\Downloads\或者D:\Downloads也是一样的错误。

**Comment by bookfere** [comment]
没能找到确切问题所在。暂时换了一个方法，请下载最新 Rolling Release 版本试试，看问题是否还存在。

**Comment by Baiyssy** [comment]
似乎还是不行，提示文件生成了，但只能看到一个0字节的文件。
我还换了D:\文件夹也是一样。

**Comment by bookfere** [comment]
所有的书都无法正常输出吗？看起来得重现错误才能修复了。

**Comment by Baiyssy** [comment]
好像是的，各种输出格式、各个路径、两台Windows 11都一样。

**Comment by Baiyssy** [comment]
还有个问题，用缓存管理器删除缓存一直不成功，
我每次都关掉Calibre，再用资源管理器删除。
错误提示：

```
calibre, version 7.7.0
错误： 无法打开正在使用的文件或文件夹: <p>无法打开文件: "C:\Users\***\AppData\Local\Temp\com.bookfere.Calibre.EbookTranslator\cache\024a4c5f891a16ebdb7adfdb2b90d0a0.db"。它已在以下程序中打开：<div>The main calibre program: C:\Program Files\Calibre2\calibre.exe

calibre 7.7  embedded-python: True
Windows-10-10.0.22635-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22635')
Python 3.11.5
Windows: ('10', '10.0.22635', 'SP0', 'Multiprocessor Free')
Interface language: zh_CN
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: Ebook Translator (2, 3, 2)
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.cache", line 146, in clear
  File "calibre_plugins.ebook_translator.lib.cache", line 118, in clean
  File "calibre_plugins.ebook_translator.lib.cache", line 113, in remove
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\***\\AppData\\Local\\Temp\\com.bookfere.Calibre.EbookTranslator\\cache\\024a4c5f891a16ebdb7adfdb2b90d0a0.db'
```

**Comment by Andy-AO** [comment]
我也遇到了相似的问题，报告了很多类似issue，包括输出时的WinError ，以及缓存管理器删除失败，还有缓存加载失败。

**Comment by Baiyssy** [comment]
缓存加载失败我没碰到过。

**Comment by Baiyssy** [comment]
这个没问题了，输出正常，缓存也可以删除。
谢谢！
