### ISSUE TITLE
[Bug report] chatgpt error 

### ISSUE THREAD

**Issue by eltabry** [bookfere/Ebook-Translator-Calibre-Plugin#265]
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 67, in translate_text
    translation = self.translator.translate(text)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.ebook_translator.engines.openai", line 92, in translate
    return self.get_result(
           ^^^^^^^^^^^^^^^^
  File "calibre_plugins.ebook_translator.engines.base", line 209, in get_result
    raise Exception(
Exception: Can not parse returned response. Raw data: 

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 196, in get_result
    br.open(request)
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 404: Not Found

{
    "error": {
        "message": "The model `gpt-4-0125-preview` does not exist or you do not have access to it.",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}

**Comment by bookfere** [comment]
Please check "[How can I access GPT-4?](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4)" to confirm if your account is eligible to access the model.

**Comment by eltabry** [comment]
i knew rulls but it is frist time i use chatgpt ..every trial i got this message
calibre, version 7.7.0 (darwin, embedded-python: True)
Translation job failed: Failed: [English > Arabic] Translating "The mystery of Holly Lane"

[English > Arabic] Translating "The mystery of Holly Lane"
InputFormatPlugin: EPUB Input running
on /Users/awakeel/Documents/calibre/Enid Blyton/The mystery of Holly Lane (18670)/The mystery of Holly Lane - Enid Blyton.epub
Found HTML cover titlepage.xhtml
Parsing all content...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Creating EPUB Output...
Translating ebook content... (this will take a while)
══════════════════════════════════════
| Diagnosis Information
══════════════════════════════════════
| Calibre Version: 7.7.0
| Plugin Version: v2.3.3
| Translation Engine: ChatGPT
| Source Language: English
| Target Language: Arabic
| Encoding: utf-8
| Cache Enabled: True
| Merging Length: 0
| Concurrent requests: 1
| Request Interval: 20.0
| Request Attempt: 3
| Request Timeout: 30.0
| Input Path: /Users/awakeel/Documents/calibre/Enid Blyton/The mystery of Holly Lane (18670)/The mystery of Holly Lane - Enid Blyton.epub
| Output Path: /Users/awakeel/Work/قناة الترجمات/تم التحويل/Arabic/The mystery of Holly Lane.epub
Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 41, in <module>
  File "site.py", line 37, in main
  File "calibre/utils/ipc/worker.py", line 215, in main
  File "calibre/utils/ipc/worker.py", line 150, in arbitrary_n
  File "calibre_plugins.ebook_translator.lib.conversion", line 235, in convert_item
  File "calibre_plugins.ebook_translator.lib.conversion", line 79, in convert_book
  File "calibre/ebooks/conversion/plumber.py", line 1281, in run
  File "calibre_plugins.ebook_translator.lib.conversion", line 70, in convert
  File "calibre_plugins.ebook_translator.lib.translation", line 255, in handle
Exception: Translation failed.

**Comment by bookfere** [comment]
The error information lacks detail for locating the issue. Could you make a test via the test button in the engine setting before translating an ebook? It may provide helpful information if an error occurs.

**Comment by mariustoicescu** [comment]
I have some problem, i have activ APi and chat gpt 4, i try chat gpt 3 and some errors.  Can you tell me if need a specific setings or ony API key ?

My error is: Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 67, in translate_text
    translation = self.translator.translate(text)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.ebook_translator.engines.openai", line 92, in translate
    return self.get_result(
           ^^^^^^^^^^^^^^^^
  File "calibre_plugins.ebook_translator.engines.base", line 209, in get_result
    raise Exception(
Exception: Can not parse returned response. Raw data: 

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 196, in get_result
    br.open(request)
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 429: Too Many Requests

{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

**Comment by mariustoicescu** [comment]
i think i find the problem, the end point link is: https://api.openai.com/v1/chat/completions

**Comment by bookfere** [comment]
The default options such as "__Concurrency limit__" and "__Interval__" are designed for the free tier. If your account has been upgraded to a paid tier, you will need to adjust these settings to suit your requirements.
