### ISSUE TITLE
[Bug report] HTTPSConnection.__init__() got an unexpected keyword argument 'key_file'

### ISSUE THREAD

**Issue by alphaville76** [bookfere/Ebook-Translator-Calibre-Plugin#269]
**Basic information**

* Operating System: **Linux Fedora**
* Calibre Version: **7.3**
* Plugin Version: **2.3.3**
* Plugin Installation: **From Calibre**

**Describe the bug**
Exception on translation. It tested with google (free) and DeepL (with api key):
```
Error: Failed to retrieve data from translate engine API.
Can not parse returned response. Raw data: 

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 196, in get_result
    br.open(request)
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_opener.py", line 193, in open
    response = urlopen(self, req, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 425, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 414, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1283, in https_open
    return self.do_open(conn_factory, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1196, in do_open
    h = http_class(host_port, timeout=req.timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HTTPSConnection.__init__() got an unexpected keyword argument 'key_file'
```

**Comment by alphaville76** [comment]
solved after updating to calibre 7.7
