### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tail'

### ISSUE THREAD

**Issue by LuXIAzoe** [bookfere/Ebook-Translator-Calibre-Plugin#27]
1. Calibre 6.17 + 
2. Error always pop-up for specific ePUB. 
3. Checked with https://www.epubvalidation.com/ epub seems correct:
 ```
The Result of the submitted file:
Filename: *******.epub

Validating using EPUB version 3.2 rules.
No errors or warnings detected.
Messages: 0 fatals / 0 errors / 0 warnings / 0 infos

EPUBCheck completed
```

Error Log:
```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 41, in <module>
  File "site.py", line 37, in main
  File "calibre/utils/ipc/worker.py", line 215, in main
  File "calibre/utils/ipc/worker.py", line 150, in arbitrary_n
  File "calibre_plugins.ebook_translator.convertion", line 124, in convert_book
  File "calibre/ebooks/conversion/plumber.py", line 1281, in run
  File "calibre_plugins.ebook_translator.convertion", line 120, in convert
  File "calibre_plugins.ebook_translator.translation", line 107, in handle
  File "calibre_plugins.ebook_translator.element", line 86, in get_original
  File "calibre_plugins.ebook_translator.element", line 29, in get_content
AttributeError: 'NoneType' object has no attribute 'tail'
```

**Comment by bookfere** [comment]
Thanks for your feedback. We fixed the bug in latest version, v1.3.2.
