### ISSUE TITLE
[错误报告] deeplx HTTP Error 403

### ISSUE THREAD

**Issue by Andy-AO** [bookfere/Ebook-Translator-Calibre-Plugin#274]
**基础信息**

* 操作系统: **Windows**
* Calibre 版本: **7.5.1**
* 插件版本：**v2.3.3**
* 插件来源: **安装自 Calibre**

使用自定义功能请求 deeplx 远程服务器 HTTP Error 403

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/ff3945c4-609b-4596-9066-889875e38608)

# 自定义json
```JavaScript
{
	"name": "deeplx(online)",
	"languages": {
		"source": {
			"English": "EN"
		},
		"target": {
			"Chinese": "ZH"
		}
	},
	"request": {
		"url": "https://api.deeplx.org/translate",
		"method": "POST",
		"headers": {
			"Content-Type": "application/json"
		},
		"data": {
			"text": "<text>",
			"source_lang": "<source>",
			"target_lang": "<target>"
		}
	},
	"response": "response['data']"
}
```
# 错误日志

```log
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 67, in translate_text
  File "calibre_plugins.ebook_translator.engines.custom", line 120, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 209, in get_result
Exception: 无法解析返回的响应。原始数据：

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 196, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

error code: 1010
```
# 额外说明

在python中请求成功，在其他软件中请求也成功，因此不是网络问题

如
```Python
import requests
import json

url = "https://api.deeplx.org/translate"

payload = json.dumps({
  "text": "Hello, world!",
  "source_lang": "auto",
  "target_lang": "ZH"
})
headers = {
  'Content-Type': 'application/json'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)

print("data:")
print(response.json().get("data"))


```

结果是

```log
D:\text\GitRepository\callDeeplx>  d:; cd 'd:\text\GitRepository\callDeeplx'; & 'd:\text\GitRepository\callDeeplx\Scripts\python.exe' 'c:\Users\Andy\.cursor\extensions\ms-python.python-2023.22.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '52427' '--' 'd:\text\GitRepository\callDeeplx\oneline.py' 
{"code":200,"id":8712290002,"data":"你好，世界","alternatives":["世界，你好","你好，世界！","大家好"]}
data:
你好，世界
```

如果使用本地的deeplx则请求成功

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/2daf9013-90f5-4bc1-be76-dcabe7770899)

**Comment by bookfere** [comment]
参考内置的 (DeepL(Free))[https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/blob/bcf812aac5f8d951bb24e80fc21f225140a790d7/engines/deepl.py#L81] 给请求标头添加一个 User-Agent。
