### ISSUE TITLE
[错误报告] 新用户 谷歌免费 任何翻译都报错。。。什么情况

### ISSUE THREAD

**Issue by lqh771** [bookfere/Ebook-Translator-Calibre-Plugin#295]
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 67, in translate_text
  File "calibre_plugins.ebook_translator.engines.google", line 52, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 209, in get_result
Exception: 无法解析返回的响应。原始数据：

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 196, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 287, in _mech_open
  File "mechanize\_opener.py", line 193, in open
  File "mechanize\_urllib2_fork.py", line 425, in _open
  File "mechanize\_urllib2_fork.py", line 414, in _call_chain
  File "mechanize\_urllib2_fork.py", line 1283, in https_open
  File "mechanize\_urllib2_fork.py", line 1240, in do_open
urllib.error.URLError: <urlopen error timed out>

**Comment by lqh771** [comment]
deepl 可以 但谷歌免费就不行

**Comment by lqh771** [comment]
deepl也不行。。

**Comment by runbing** [comment]
你安装的插件是哪个版本？

**Comment by bookfere** [comment]
由于错误信息中没有足够的线索排查问题，你可能需要按照下面的步骤再排查一下：

1. 你使用的是否是最新版本插件，如果不是请下载安装最新版本插件；
2. 如果翻译服务需要使用代理访问，你需要设置可正常使用的代理；
3. 你可使用插件设置中的测试功能测试，看能否出现更具体的错误信息。

**Comment by gengmu** [comment]
应该calibre版本问题，我安装7.10.0后出现上面的问题，退回7.7.0版本后正常了

**Comment by wenzy** [comment]
我退回7.7.0也是一样不行。
google free不行；deepl free 有带宽和数量限制；microsoft edge free可以。

**Comment by laydone** [comment]
google free 全量报错信息,目测是因为人机验证过不了~~
```
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 67, in translate_text
  File "calibre_plugins.ebook_translator.engines.google", line 53, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 210, in get_result
Exception: 无法解析返回的响应。原始数据：

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 197, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 429: Too Many Requests

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="initial-scale=1"><title>https://translate.googleapis.com/translate_a/single?client=gtx&amp;sl=auto&amp;tl=zh-CN&amp;dt=t&amp;dj=1&amp;q=Hello+World%21</title></head>
<body style="font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px; overscroll-behavior:contain;" onload="e=document.getElementById('captcha');if(e){e.focus();} if(solveSimpleChallenge) {solveSimpleChallenge(,);}">
<div style="max-width:400px;">
<hr noshade size="1" style="color:#ccc; background-color:#ccc;"><br>
<form id="captcha-form" action="index" method="post">
<noscript>
<div style="font-size:13px;">
  In order to continue, please enable javascript on your web browser.
</div>
</noscript>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script>var submitCallback = function(response) {document.getElementById('captcha-form').submit();};</script>
<div id="recaptcha" class="g-recaptcha" data-sitekey="6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b" data-callback="submitCallback" data-s="k8JLqT28f-cKUMPih8WrTeXcuRqIWBnL2veB-bosn-JaEthogF5VjmbyiPpHswmupgkhO1DlVZ4v-2l4j2r6lTZYjanyeJXJ873lzNLMRXkXxVnNAZyzZaBqApDzqP6W_CH4jRFsNIsRvMeTptpViqDLmM0MqdrDDt4zymHFL0KcKXxmTXvuMXXy5fyXQ0z-OV1rhpwCFdOs5e_4LtcqoIYIkFyoNIOYB-kT5SOyH2YWjL-qohlGYloY_p0kXugciW_mEe1QUfxKP0bFONTS_Yx-aZyl-3Y"></div>

<input type='hidden' name='q' value='EgRnVUl3GIbivLcGIjD_X3UDL7nro_zot5RsSP5aGZhVEKn_ZURlsHNCVBnOwSYzVPsJQfpjnL7wivffTbcyAXJaAUM'><input type="hidden" name="continue" value="https://translate.googleapis.com/translate_a/single?client=gtx&amp;sl=auto&amp;tl=zh-CN&amp;dt=t&amp;dj=1&amp;q=Hello+World%21">
</form>
<hr noshade size="1" style="color:#ccc; background-color:#ccc;">

<div style="font-size:13px;">
<b>About this page</b><br><br>

Our systems have detected unusual traffic from your computer network.  This page checks to see if it&#39;s really you sending the requests, and not a robot.  <a href="#" onclick="document.getElementById('infoDiv').style.display='block';">Why did this happen?</a><br><br>

<div id="infoDiv" style="display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;">
This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the <a href="//www.google.com/policies/terms/">Terms of Service</a>. The block will expire shortly after those requests stop.  In the meantime, solving the above CAPTCHA will let you continue to use our services.<br><br>This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests.  If you share your network connection, ask your administrator for help &mdash; a different computer using the same IP address may be responsible.  <a href="//support.google.com/websearch/answer/86640">Learn more</a><br><br>Sometimes you may be asked to solve the CAPTCHA if you are using advanced terms that robots are known to use, or sending requests very quickly.
</div>

IP address: xxx.xx.xx.xx<br>Time: xxxxxx<br>URL: https://translate.googleapis.com/translate_a/single?client=gtx&amp;sl=auto&amp;tl=zh-CN&amp;dt=t&amp;dj=1&amp;q=Hello+World%21<br>
</div>
</div>
</body>
</html>
```
