### ISSUE TITLE
[Bug report] Deepl api stuck when run out of usage limit

### ISSUE THREAD

**Issue by Dwtexe** [bookfere/Ebook-Translator-Calibre-Plugin#334]
**Basic information**

* Operating System: **Windows**
* Calibre Version: **7.13**
* Plugin Version: **latest**
* Plugin Installation: **From Calibre**

**Describe the bug**
When translating with Deepl, api keys do not change sequentially. when an api key runs out of usage limit, it gets stuck instead of switching to a new one.

**Comment by Dwtexe** [comment]
Hata: Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.lib.translation", line 136, in _translate_text
  File "calibre_plugins.ebook_translator.engines.deepl", line 49, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 210, in get_result
