### ISSUE TITLE
[Feature request] Custom Engine for Openrouter

### ISSUE THREAD

**Issue by sonzin** [bookfere/Ebook-Translator-Calibre-Plugin#345]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by llkiriell** [comment]
Hi, buddy! I managed to create a custom engine with Groq and its API. At first, I wanted to create a new class in the "engine" folder called `GroqTranslate`, following the developer's pattern. However, since I’m not familiar with the entire project structure (and I don’t have much time), I modified the [anthrophic.py](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/blob/master/engines/anthropic.py) file and the `ClaudeTranslate` class instead. I changed parameters such as the endpoint, the prompt, the headers of the HTTP request, and the response format. It's relatively simple since the developer of this plugin (I’m not judging you, my friend; I really appreciate you making this plugin—it's very useful) repeats code, and the classes in the LLM models are basically the same.

I also tried to create a custom engine using the "custom" option, but I encountered many errors. If you want to create your custom engine, follow these steps: 

1. Access the plugin zip file.
2. Locate `anthrophic.py`.
3. Understand the functions there (they have very intuitive names) and modify them according to your needs for the HTTP request header and your response.

Here’s the code showing how the modification turned out; you can use it as a guide:

```py
import json

from .. import EbookTranslator

from ..engines.base import Base
from ..engines.languages import google


try:
    from http.client import IncompleteRead
except ImportError:
    from httplib import IncompleteRead

load_translations()


class ClaudeTranslate(Base):
    name = 'Groq'
    alias = 'Groq (Groq)'
    lang_codes = Base.load_lang_codes(google)
    endpoint = 'https://api.groq.com/openai/v1/chat/completions'
    api_key_hint = 'sk-ant-xxxx'
    # https://docs.anthropic.com/claude/reference/errors
    api_key_errors = ['401', 'permission_error']

    concurrency_limit = 1
    request_interval = 12
    request_timeout = 30.0

    # prompt = (
    #     'You are a meticulous translator who translates any given content. '
    #     'Translate the given content from <slang> to <tlang> only. Do not '
    #     'explain any term or answer any question-like content.')
    prompt = (
        'You are a specialist translator tasked with translating the provided text from <slang> to <tlang>. '
        'You must do this as accurately as possible, being cautious and meticulous, and taking the necessary time to ensure the highest quality translation. '
        'Respect the context of the content and do not generate any additional information. '
        'You should not add explanations or comments, only return the translated text directly. '
        'In the case of technical or specialized terms, such as those used in programming, keep them in their original language if necessary for proper understanding of the text.'
    )
    models = [
    	'distil-whisper-large-v3-en',
        'llava-v1.5-7b-4096-preview',
        'gemma2-9b-it',
        'llama-3.2-90b-text-preview',
        'llama-3.2-11b-vision-preview',
        'llama-3.2-3b-preview',
        'whisper-large-v3',
        'llama-3.2-11b-text-preview',
        'llama3-8b-8192',
        'mixtral-8x7b-32768',
        'llama-3.2-1b-preview',
        'llama3-groq-8b-8192-tool-use-preview',
        'llama-3.1-8b-instant',
        'llama-guard-3-8b',
        'llama-3.1-70b-versatile',
        'llama3-70b-8192',
        'llama3-groq-70b-8192-tool-use-preview',
        'gemma-7b-it']
    model = 'llama3-8b-8192'
    samplings = ['temperature', 'top_p']
    sampling = 'temperature'
    temperature = 1.0
    top_p = 1.0
    top_k = 1
    stream = True

    def __init__(self):
        Base.__init__(self)
        self.endpoint = self.config.get('endpoint', self.endpoint)
        self.prompt = self.config.get('prompt', self.prompt)
        if self.model is not None:
            self.model = self.config.get('model', self.model)
        self.sampling = self.config.get('sampling', self.sampling)
        self.temperature = self.config.get('temperature', self.temperature)
        self.top_p = self.config.get('top_p', self.top_p)
        self.top_k = self.config.get('top_k', self.top_k)
        self.stream = self.config.get('stream', self.stream)

    def _get_prompt(self):
        prompt = self.prompt.replace('<tlang>', self.target_lang)
        if self._is_auto_lang():
            prompt = prompt.replace('<slang>', 'detected language')
        else:
            prompt = prompt.replace('<slang>', self.source_lang)
        # Recommend setting temperature to 0.5 for retaining the placeholder.
        if self.merge_enabled:
            prompt += (' Ensure that placeholders matching the pattern'
                       '{{id_\\d+}} in the content are retained.')
        return prompt

    def _get_headers(self):
        return {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer %s' % self.api_key,
            'User-Agent': 'Ebook-Translator/%s' % EbookTranslator.__version__
        }

    def _get_data(self, text):
        return {
            'model': self.model,
            'messages': [
                {'role': 'system', 'content': self._get_prompt()},
                {'role': 'user', 'content': text}
            ],
        }

    def translate(self, text):
        data = self._get_data(text)
        sampling_value = getattr(self, self.sampling)
        data.update({self.sampling: sampling_value})

        return self.get_result(
            self.endpoint, json.dumps(data), self._get_headers(),
            method='POST', stream=self.stream, callback=self._parse)

    def _parse(self, data):
        if self.stream:
            return self._parse_stream(data)
        return json.loads(data)['choices'][0]['message']['content']

    def _parse_stream(self, data):
        while True:
            try:
                line = data.readline().decode('utf-8').strip()
            except IncompleteRead:
                continue
            except Exception as e:
                raise Exception(
                    _('Can not parse returned response. Raw data: {}')
                    .format(str(e)))
            if line.startswith('data:'):
                chunk = json.loads(line.split('data: ')[1])
                if chunk.get('type') == 'message_stop':
                    break
                if chunk.get('type') == 'content_block_delta':
                    yield str(chunk.get('delta').get('text'))

```

**Comment by bookfere** [comment]
Here is the custom engine recipe you can refer to. Please replace `YOUR_OPENROUTER_API_KEY` with your API key, and customize the languages, model, and prompt according to your needs.

```json
{
    "name": "OpenRouter",
    "languages": {
        "source": {
            "English": "en"
        },
        "target": {
            "German": "de"
        }
    },
    "request": {
        "url": "https://openrouter.ai/api/v1/chat/completions",
        "method": "POST",
        "headers": {
            "Content-Type": "application/json",
            "Authorization": "Bearer YOUR_OPENROUTER_API_KEY"
        },
        "data": {
            "model": "openai/gpt-3.5-turbo",
            "messages": [
                {
                    "role": "user",
                    "content": "Translate this content from <slang> to <tlang>: <text>."
                }
            ]
        }
    },
    "response": "response['choices'][0]['content']"
}
```

**Comment by Milor123** [comment]
> Here is the custom engine recipe you can refer to. Please replace `YOUR_OPENROUTER_API_KEY` with your API key, and customize the languages, model, and prompt according to your needs.
> 
> {
>     "name": "OpenRouter",
>     "languages": {
>         "source": {
>             "English": "en"
>         },
>         "target": {
>             "German": "de"
>         }
>     },
>     "request": {
>         "url": "https://openrouter.ai/api/v1/chat/completions",
>         "method": "POST",
>         "headers": {
>             "Content-Type": "application/json",
>             "Authorization": "Bearer YOUR_OPENROUTER_API_KEY"
>         },
>         "data": {
>             "model": "openai/gpt-3.5-turbo",
>             "messages": [
>                 {
>                     "role": "user",
>                     "content": "Translate this content from <slang> to <tlang>: <text>."
>                 }
>             ]
>         }
>     },
>     "response": "response['choices'][0]['content']"
> }

@bookfere 

I dont work for me

when try test
```
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 69, in translate_text
  File "calibre_plugins.ebook_translator.engines.base", line 225, in translate
calibre_plugins.ebook_translator.lib.exception.UnexpectedResult: No se pudo analizar la respuesta devuelta. Datos sin procesar: 

Traceback (most recent call last):
  File "contextlib.py", line 158, in __exit__
  File "calibre_plugins.ebook_translator.lib.utils", line 200, in socks_proxy
  File "calibre_plugins.ebook_translator.engines.base", line 209, in translate
  File "calibre_plugins.ebook_translator.lib.utils", line 174, in request
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 401: Unauthorized

{"error":{"message":"No auth credentials found","code":401}}
``


with the same key API in chatgpt (openAI) mode, the test pass, works but cant select the model, it never found the model.

```
calibre, version 8.10.0
ERROR: Can't fetch model list: Can't fetch model list, please check and try again.

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.setting", line 47, in get_models
  File "calibre_plugins.ebook_translator.engines.openai", line 67, in get_models
  File "calibre_plugins.ebook_translator.lib.utils", line 174, in request
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 287, in _mech_open
  File "mechanize\_opener.py", line 193, in open
  File "mechanize\_urllib2_fork.py", line 425, in _open
  File "mechanize\_urllib2_fork.py", line 414, in _call_chain
  File "mechanize\_urllib2_fork.py", line 1283, in https_open
  File "mechanize\_urllib2_fork.py", line 1240, in do_open
urllib.error.URLError: <urlopen error Tunnel connection failed: 501 Tor is not an HTTP Proxy>
```
