### ISSUE TITLE
[Bug report] Unable to create new epub translated file

### ISSUE THREAD

**Issue by Ludko4444** [bookfere/Ebook-Translator-Calibre-Plugin#352]
**Basic information**
Hello. This add-on works like a charm. However I have problem with translating one epub file to my own native language. I get error:
Time consuming: 0.01 minutes
Translation completed.
Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\utils\ipc\worker.py", line 150, in arbitrary_n
  File "calibre_plugins.ebook_translator.lib.conversion", line 242, in convert_item
  File "calibre_plugins.ebook_translator.lib.conversion", line 86, in convert_book
  File "calibre\ebooks\conversion\plumber.py", line 1307, in run
  File "calibre_plugins.ebook_translator.lib.conversion", line 74, in convert
  File "calibre_plugins.ebook_translator.lib.element", line 683, in add_translations
  File "calibre_plugins.ebook_translator.lib.element", line 269, in add_translation
  File "src/lxml/etree.pyx", line 1655, in lxml.etree.__ContentOnlyElement.set
  File "src/lxml/etree.pyx", line 1651, in lxml.etree.__ContentOnlyElement._raiseImmutable
TypeError: this element does not have children or attributes

**Comment by bookfere** [comment]
Could you upload a sample related to this error? You can either upload it here or send it to me via email.
