### ISSUE TITLE
[Bug report] Gemini - translation bug

### ISSUE THREAD

**Issue by iamnvt** [bookfere/Ebook-Translator-Calibre-Plugin#365]
it shows below error when using Gemini Flash:

Error: Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.lib.translation", line 134, in translate_text
  File "calibre_plugins.ebook_translator.engines.base", line 182, in translate
calibre_plugins.ebook_translator.lib.exception.UnexpectedResult: Can not parse returned response. Raw data: 

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 171, in translate
  File "calibre_plugins.ebook_translator.engines.google", line 324, in get_result
AttributeError: 'bytes' object has no attribute 'read'

**Comment by bookfere** [comment]
Thanks for your feedback. I have fixed the bug. Please try the Rolling Release version.

**Comment by sonkite225** [comment]
> Thanks for your feedback. I have fixed the bug. Please try the Rolling Release version.

maybe a dumb question, but what do you mean with rolling release version? download zip from code on mainpage?

**Comment by bookfere** [comment]
@sonkite225

Yes, once a commit occurs, a rolling release update will appear on the main page. You need to download and load it into Calibre manually (here is the [instructions](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/wiki/English#installation)).
