### ISSUE TITLE
error: bad escape \H at position 74

### ISSUE THREAD

**Issue by chenweil** [bookfere/Ebook-Translator-Calibre-Plugin#40]
I use a plugin to translate a book:[Laravel: Up & Running](https://www.oreilly.com/library/view/laravel-up/9781492041207/)

* calibre:6.17.0
* [Plugin](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin): v1.3.7
---

```
Traceback (most recent call last):
  File "sre_parse.py", line 1039, in parse_template
KeyError: '\\H'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 41, in <module>
  File "site.py", line 37, in main
  File "calibre/utils/ipc/worker.py", line 215, in main
  File "calibre/utils/ipc/worker.py", line 150, in arbitrary_n
  File "calibre_plugins.ebook_translator.convertion", line 123, in convert_book
  File "calibre/ebooks/conversion/plumber.py", line 1281, in run
  File "calibre_plugins.ebook_translator.convertion", line 119, in convert
  File "calibre_plugins.ebook_translator.translation", line 140, in handle
  File "calibre_plugins.ebook_translator.element", line 119, in apply_translation
  File "calibre_plugins.ebook_translator.element", line 51, in add_translation
  File "re.py", line 209, in sub
  File "re.py", line 326, in _subx
  File "re.py", line 317, in _compile_repl
  File "sre_parse.py", line 1042, in parse_template
re.error: bad escape \H at position 74
```
---
[log:job.log](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/11459187/job.log)

**Comment by bookfere** [comment]
The bug has been fixed. Please try the test version of the plugin below and let me know if the problem has disappeared.

[ebook-translator_20230512151050.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/11460405/ebook-translator_20230512151050.zip)

**Comment by chenweil** [comment]
> The bug has been fixed. Please try the latest version, v1.3.8.

__I tested it and the problem is solved in the new version. Thanks。
