### ISSUE TITLE
Incomplete Read

### ISSUE THREAD

**Issue by Jackie00765** [bookfere/Ebook-Translator-Calibre-Plugin#50]
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/103828365/e950229e-b126-4db2-9203-5cf6a406290d)

**Comment by Jackie00765** [comment]
Traceback (most recent call last):
  File "http\client.py", line 565, in _get_chunk_left
  File "http\client.py", line 532, in _read_next_chunk_size
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "http\client.py", line 605, in _readinto_chunked
  File "http\client.py", line 567, in _get_chunk_left
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.chatgpt", line 87, in parse_stream
  File "mechanize\_response.py", line 224, in readline
  File "socket.py", line 705, in readinto
  File "http\client.py", line 502, in readinto
  File "http\client.py", line 621, in _readinto_chunked
http.client.IncompleteRead: IncompleteRead(2489 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.advanced", line 148, in translate_paragraphs
  File "calibre_plugins.ebook_translator.translation", line 166, in handle
  File "calibre_plugins.ebook_translator.request", line 37, in run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 641, in run_until_complete
  File "calibre_plugins.ebook_translator.request", line 34, in create_tasks
  File "calibre_plugins.ebook_translator.request", line 23, in create_worker
  File "calibre_plugins.ebook_translator.translation", line 161, in process_translation
  File "calibre_plugins.ebook_translator.translation", line 122, in _prepare_translation
  File "calibre_plugins.ebook_translator.engines.chatgpt", line 89, in parse_stream
Exception: 無法剖析返回的回應。原始資料：IncompleteRead(2489 bytes read)

**Comment by bookfere** [comment]
Thanks for your feedback. We will address this issue in a future version.
