### ISSUE TITLE
[bug]2.0.0及以后的版本中，在插件设置页面点击保存会导致刚新建的自定义翻译引擎从配置文件中消失

### ISSUE THREAD

**Issue by WeeAris** [bookfere/Ebook-Translator-Calibre-Plugin#56]
问题描述：
新建一个自定义翻译引擎，保存，设置中选择好刚才新建的翻译引擎，并设置好偏好语言，保存，关闭插件设置页面，再打开插件设置，发现翻译引擎列表中没有刚才新建的翻译引擎，但偏好语言设置却保留了下来。关闭插件和calibre，重新打开calibre，点击插件的设置后弹出如下错误
```
calibre, version 6.19.1
错误： 未处理的异常: <b>TypeError</b>:SourceLang.refresh[dict, str, bool].emit(): argument 1 has unexpected type 'NoneType'

calibre 6.19.1  embedded-python: True
Linux-6.3.5-201.fsync.fc37.x86_64-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '6.3.5-201.fsync.fc37.x86_64', '#1 SMP PREEMPT_DYNAMIC Thu Jun  1 09:31:01 UTC 2023')
Python 3.10.1
Interface language: zh_CN
Successfully initialized third party plugins: Chinese Text Conversion (3, 0, 1) && Ebook Translator (2, 0, 0) && EpubSplit (3, 6, 0)
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.ui", line 115, in show_setting
    window = TranslationSetting(self, self.gui, self.icon)
  File "calibre_plugins.ebook_translator.setting", line 51, in __init__
    self.main_layout()
  File "calibre_plugins.ebook_translator.setting", line 58, in main_layout
    tab_2 = self.tabs.addTab(self.layout_engine(), _('Engine'))
  File "calibre_plugins.ebook_translator.setting", line 89, in scroll_widget
    scroll_area.setWidget(func(self))
  File "calibre_plugins.ebook_translator.setting", line 527, in layout_engine
    choose_default_engine(default_index)
  File "calibre_plugins.ebook_translator.setting", line 515, in choose_default_engine
    self.source_lang.refresh.emit(
TypeError: SourceLang.refresh[dict, str, bool].emit(): argument 1 has unexpected type 'NoneType'

```
通过跟踪查看插件的配置文件发现，在刚添加完翻译引擎时，引擎设置确实正常保存了，但如果在关闭设置页面前点击设置页面的保存按钮，刚添加完的翻译引擎就从配置文件中消失了，此时如果查看自定义页面也会发现自定义引擎列表中没有刚添加的引擎选项。

**Comment by bookfere** [comment]
试试这个版本，看是否还有问题：

[ebook-translator-202306102326.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/11712737/ebook-translator-202306102326.zip)

**Comment by WeeAris** [comment]
> 试试这个版本，看是否还有问题：
> 
> [ebook-translator-202306102326.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/11712737/ebook-translator-202306102326.zip)

测试没问题了
