### ISSUE TITLE
有部分书翻译到一半会抛出异常

### ISSUE THREAD

**Issue by fakechris** [bookfere/Ebook-Translator-Calibre-Plugin#61]
日志是这样的，看起来是一行空的字符串导致的

Original: 
Failed to retreive data from translate engine API.
Will retry in 5 seconds.

[2023-06-12 09:09:11] Retrying 1 ... (timeout is 300 seconds).

Failed to retreive data from translate engine API.
Will retry in 10 seconds.

[2023-06-12 09:09:22] Retrying 2 ... (timeout is 300 seconds).
Failed to retreive data from translate engine API.
Will retry in 30 seconds.

[2023-06-12 09:09:53] Retrying 3 ... (timeout is 300 seconds).

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 107, in get_result
  File "calibre_plugins.ebook_translator.engines.google", line 44, in parse
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 65, in _translate_text
  File "calibre_plugins.ebook_translator.engines.google", line 41, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 114, in get_result
Exception: Can not parse returned response. Raw data: [null,null,"en",null,null,null,0,[],[["en"],null,[0],["en"]]] 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 107, in get_result
  File "calibre_plugins.ebook_translator.engines.google", line 44, in parse
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 65, in _translate_text
  File "calibre_plugins.ebook_translator.engines.google", line 41, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 114, in get_result
Exception: Can not parse returned response. Raw data: [null,null,"en",null,null,null,0,[],[["en"],null,[0],["en"]]] 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 107, in get_result
  File "calibre_plugins.ebook_translator.engines.google", line 44, in parse
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 65, in _translate_text
  File "calibre_plugins.ebook_translator.engines.google", line 41, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 114, in get_result
Exception: Can not parse returned response. Raw data: [null,null,"en",null,null,null,0,[],[["en"],null,[0],["en"]]] 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 107, in get_result
  File "calibre_plugins.ebook_translator.engines.google", line 44, in parse
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 65, in _translate_text
  File "calibre_plugins.ebook_translator.engines.google", line 41, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 114, in get_result
Exception: Can not parse returned response. Raw data: [null,null,"en",null,null,null,0,[],[["en"],null,[0],["en"]]] 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 41, in <module>
  File "site.py", line 37, in main
  File "calibre/utils/ipc/worker.py", line 215, in main
  File "calibre/utils/ipc/worker.py", line 150, in arbitrary_n
  File "calibre_plugins.ebook_translator.convertion", line 123, in convert_book
  File "calibre/ebooks/conversion/plumber.py", line 1281, in run
  File "calibre_plugins.ebook_translator.convertion", line 119, in convert
  File "calibre_plugins.ebook_translator.translation", line 136, in handle
  File "calibre_plugins.ebook_translator.concurrency", line 23, in async_
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 641, in run_until_complete
  File "calibre_plugins.ebook_translator.concurrency", line 20, in main
  File "calibre_plugins.ebook_translator.concurrency", line 11, in worker
  File "calibre_plugins.ebook_translator.translation", line 92, in _get_translation
  File "calibre_plugins.ebook_translator.translation", line 78, in _translate_text
  File "calibre_plugins.ebook_translator.translation", line 78, in _translate_text
  File "calibre_plugins.ebook_translator.translation", line 78, in _translate_text
  File "calibre_plugins.ebook_translator.translation", line 69, in _translate_text
Exception: Failed to retreive data from translate engine API. Can not parse returned response. Raw data: [null,null,"en",null,null,null,0,[],[["en"],null,[0],["en"]]] 'NoneType' object is not iterable

**Comment by bookfere** [comment]
使用的是最新版本插件吗？

**Comment by fakechris** [comment]
的确不是最新版本的，抱歉，我升级之后再确认一下
