### ISSUE TITLE
DeepL, DeepL free and DeepL pro not working 

### ISSUE THREAD

**Issue by lelediaz** [bookfere/Ebook-Translator-Calibre-Plugin#70]
Hey,
I wanted to use DeepL as translator to translate books I have stored in Calibre, but each one of DeepL´s choices does not work. I already added the API Key that is needed for the DeepL and DeepL pro action but it's still not working. I always get this message after a few seconds of trying to translate: 
calibre, version 6.20.0 (darwin, embedded-python: True)
Translation Failed: Failed: Failed to retreive data from translate engine API. Can not parse returned response. Raw data: HTTP Error 403: Forbidden

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 144, in get_result
    self.br.open(request)
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 68, in _translate_text
    return self.translator.translate(text)
  File "calibre_plugins.ebook_translator.engines.deepl", line 48, in translate
    return self.get_result(
  File "calibre_plugins.ebook_translator.engines.base", line 156, in get_result
    raise Exception(
Exception: Can not parse returned response. Raw data: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 144, in get_result
    self.br.open(request)
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 68, in _translate_text
    return self.translator.translate(text)
  File "calibre_plugins.ebook_translator.engines.deepl", line 48, in translate
    return self.get_result(
  File "calibre_plugins.ebook_translator.engines.base", line 156, in get_result
    raise Exception(
Exception: Can not parse returned response. Raw data: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 144, in get_result
    self.br.open(request)
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 68, in _translate_text
    return self.translator.translate(text)
  File "calibre_plugins.ebook_translator.engines.deepl", line 48, in translate
    return self.get_result(
  File "calibre_plugins.ebook_translator.engines.base", line 156, in get_result
    raise Exception(
Exception: Can not parse returned response. Raw data: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 144, in get_result
    self.br.open(request)
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 68, in _translate_text
    return self.translator.translate(text)
  File "calibre_plugins.ebook_translator.engines.deepl", line 48, in translate
    return self.get_result(
  File "calibre_plugins.ebook_translator.engines.base", line 156, in get_result
    raise Exception(
Exception: Can not parse returned response. Raw data: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.advanced", line 159, in translate_paragraphs
    translation.handle(paragraphs)
  File "calibre_plugins.ebook_translator.translation", line 162, in handle
    async_request.run()
  File "calibre_plugins.ebook_translator.request", line 37, in run
    asyncio.run(self.create_tasks())
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 641, in run_until_complete
  File "calibre_plugins.ebook_translator.request", line 34, in create_tasks
    await asyncio.gather(*self.tasks)
  File "calibre_plugins.ebook_translator.request", line 23, in create_worker
    self.process_translation(paragraph)
  File "calibre_plugins.ebook_translator.translation", line 157, in process_translation
    self._prepare_translation(paragraph)
  File "calibre_plugins.ebook_translator.translation", line 115, in _prepare_translation
    translation = self._translate_text(original)
  File "calibre_plugins.ebook_translator.translation", line 101, in _translate_text
    return self._translate_text(text, count, interval)
  File "calibre_plugins.ebook_translator.translation", line 101, in _translate_text
    return self._translate_text(text, count, interval)
  File "calibre_plugins.ebook_translator.translation", line 101, in _translate_text
    return self._translate_text(text, count, interval)
  File "calibre_plugins.ebook_translator.translation", line 91, in _translate_text
    raise Exception('{} {}'.format(message, str(e)))
Exception: Failed to retreive data from translate engine API. Can not parse returned response. Raw data: HTTP Error 403: Forbidden

Do I have the wrong version of Calibre? Do I need the newest calibre or an older version to make it work? Would highly need a response, since this tool is great and I really need it :)

**Comment by bookfere** [comment]
The error information indicates that you have no permission to access the DeepL API. Perhaps you used an invalid API Key? I suggest you check if the API key is in the correct format: 

```
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:fx
```

**Comment by lelediaz** [comment]
thanks for the response, I checked the API key but it's in the format you have written before, so I don't know what the problem is here, but now DeepL free is working fine only DeepL and the pro aren't working, anyway, thanks again

**Comment by bookfere** [comment]
<img width="592" alt="deepl" src="https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/29969316/79498cd2-2eb5-430f-baea-34583e6311a8">

I tested it again, and there doesn't seem to be any problem.

**Comment by lelediaz** [comment]
Hey,
Alright good to know, so I have the DeepL pro plan (advanced) it may be this why it doesn't work, since it's not DeepL API, although I have a key that can be used for any Cat Tools and stuff like that. 
But I found a way to use DeepL free without any breaks although it's stated to be unstable in the plugin, but it works fine for me here. 
You may be able to find a way in the future to make it happen that DeepL pro (not deepL API) can be used here to by login in to deep pro or so, that would be great too.

**Comment by Flamarket** [comment]
> Привет, хорошо, приятно знать, поэтому у меня есть план DeepL pro (расширенный), возможно, поэтому он не работает, поскольку это не DeepL API, хотя у меня есть ключ, который можно использовать для любых инструментов Cat и тому подобного. что. Но я нашел способ использовать DeepL бесплатно без каких-либо перерывов, хотя в плагине он заявлен как нестабильный, но здесь у меня он работает нормально. Возможно, в будущем вы сможете найти способ сделать так, чтобы DeepL pro (а не deepL API) можно было использовать здесь для входа в Deep Pro или что-то в этом роде, это тоже было бы здорово.

Can you please tell me how I can use deepl free without interruptions? I have the same problem(
