### ISSUE TITLE
原始数据：'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte

### ISSUE THREAD

**Issue by michaelpopes** [bookfere/Ebook-Translator-Calibre-Plugin#79]
目前又出现了如下错误，请看一下，谢谢！

原文：Everything about tulip sex seems orderly and intelligible; there is none of the occult mystery that attends the sexuality of, say, a Bourbon rose or a doubled peony. Those two are flowers in which one imagines a bumblebee being forced to feel his way around in the dark, stumbling blindly, drunkenly, getting himself all tangled in their innumerable petals. Which is precisely the idea, of course. But it is not the tulip’s idea.
无法从翻译引擎API获取数据。
5 秒后重试。
[2023-06-28 19:07:08] 正在重试 1 ...（60秒后超时）
无法从翻译引擎API获取数据。
10 秒后重试。

[2023-06-28 19:07:18] 正在重试 2 ...（60秒后超时）
无法从翻译引擎API获取数据。
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 170, in get_result
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 55, in _translate_text
  File "calibre_plugins.ebook_translator.engines.deepl", line 122, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 179, in get_result
Exception: 无法解析返回的响应。原始数据：'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 170, in get_result
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 55, in _translate_text
  File "calibre_plugins.ebook_translator.engines.deepl", line 122, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 179, in get_result
Exception: 无法解析返回的响应。原始数据：'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 170, in get_result
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 55, in _translate_text
  File "calibre_plugins.ebook_translator.engines.deepl", line 122, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 179, in get_result
Exception: 无法解析返回的响应。原始数据：'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\utils\ipc\worker.py", line 150, in arbitrary_n
  File "calibre_plugins.ebook_translator.convertion", line 93, in convert_book
  File "calibre\ebooks\conversion\plumber.py", line 1281, in run
  File "calibre_plugins.ebook_translator.convertion", line 86, in convert
  File "calibre_plugins.ebook_translator.translation", line 149, in handle
  File "calibre_plugins.ebook_translator.request", line 37, in run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 641, in run_until_complete
  File "calibre_plugins.ebook_translator.request", line 34, in create_tasks
  File "calibre_plugins.ebook_translator.request", line 22, in create_worker
  File "calibre_plugins.ebook_translator.translation", line 144, in process_translation
  File "calibre_plugins.ebook_translator.translation", line 102, in _prepare_translation
  File "calibre_plugins.ebook_translator.translation", line 88, in _translate_text
  File "calibre_plugins.ebook_translator.translation", line 88, in _translate_text
  File "calibre_plugins.ebook_translator.translation", line 78, in _translate_text
Exception: 无法从翻译引擎API获取数据。 无法解析返回的响应。原始数据：'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte

**Comment by anartigone** [comment]
我也遇到了相同问题，引擎选择DeepL的时候就会报错，Google正常。目测应该是DeepL引擎接口那边有改动。

**Comment by parataxia** [comment]
I have same errors, it worked a week ago but now improper encoding from server/plugin persists.. perhaps DeepL blocked the client side protocol.. I hope it gets resolved soon enough.
