### ISSUE TITLE
Failed to retreive data from translate engine API. 是什么问题？

### ISSUE THREAD

**Issue by hrdg** [bookfere/Ebook-Translator-Calibre-Plugin#88]
```
==============================
Start to translate ebook content
==============================
Total items: 11749
------------------------------
Original: Stock
Failed to retreive data from translate engine API.
Will retry in 5 seconds.
[2023-07-16 13:01:46] Retrying 1 ... (timeout is 10 seconds).
Failed to retreive data from translate engine API.
Will retry in 10 seconds.
[2023-07-16 13:01:56] Retrying 2 ... (timeout is 10 seconds).
Failed to retreive data from translate engine API.
Will retry in 30 seconds.
[2023-07-16 13:01:26] Retrying 3 ... (timeout is 10 seconds).
Failed to retreive data from translate engine API.
Traceback (most recent call last):
  File "mechanize/_urllib2_fork.py", line 1236, in do_open
  File "http/client.py", line 1282, in request
  File "http/client.py", line 1328, in _send_request
  File "http/client.py", line 1277, in endheaders
  File "http/client.py", line 1037, in _send_output
  File "http/client.py", line 975, in send
  File "http/client.py", line 1454, in connect
  File "ssl.py", line 512, in wrap_socket
  File "ssl.py", line 1070, in _create
  File "ssl.py", line 1341, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 167, in get_result
    self.br.open(request)
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 287, in _mech_open
  File "mechanize/_opener.py", line 193, in open
  File "mechanize/_urllib2_fork.py", line 425, in _open
  File "mechanize/_urllib2_fork.py", line 414, in _call_chain
  File "mechanize/_urllib2_fork.py", line 1283, in https_open
  File "mechanize/_urllib2_fork.py", line 1240, in do_open
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:997)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 55, in _translate_text
    return self.translator.translate(text)
  File "calibre_plugins.ebook_translator.engines.chatgpt", line 88, in translate
    return self.get_result(
  File "calibre_plugins.ebook_translator.engines.base", line 179, in get_result
    raise Exception(
Exception: Can not parse returned response. Raw data: <urlopen error EOF occurred in violation of protocol (_ssl.c:997)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mechanize/_urllib2_fork.py", line 1236, in do_open
  File "http/client.py", line 1282, in request
  File "http/client.py", line 1328, in _send_request
  File "http/client.py", line 1277, in endheaders
  File "http/client.py", line 1037, in _send_output
  File "http/client.py", line 975, in send
  File "http/client.py", line 1454, in connect
  File "ssl.py", line 512, in wrap_socket
  File "ssl.py", line 1070, in _create
  File "ssl.py", line 1341, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 167, in get_result
    self.br.open(request)
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 287, in _mech_open
  File "mechanize/_opener.py", line 193, in open
  File "mechanize/_urllib2_fork.py", line 425, in _open
  File "mechanize/_urllib2_fork.py", line 414, in _call_chain
  File "mechanize/_urllib2_fork.py", line 1283, in https_open
  File "mechanize/_urllib2_fork.py", line 1240, in do_open
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:997)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 55, in _translate_text
    return self.translator.translate(text)
  File "calibre_plugins.ebook_translator.engines.chatgpt", line 88, in translate
    return self.get_result(
  File "calibre_plugins.ebook_translator.engines.base", line 179, in get_result
    raise Exception(
Exception: Can not parse returned response. Raw data: <urlopen error EOF occurred in violation of protocol (_ssl.c:997)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mechanize/_urllib2_fork.py", line 1236, in do_open
  File "http/client.py", line 1282, in request
  File "http/client.py", line 1328, in _send_request
  File "http/client.py", line 1277, in endheaders
  File "http/client.py", line 1037, in _send_output
  File "http/client.py", line 975, in send
  File "http/client.py", line 1454, in connect
  File "ssl.py", line 512, in wrap_socket
  File "ssl.py", line 1070, in _create
  File "ssl.py", line 1341, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 167, in get_result
    self.br.open(request)
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 287, in _mech_open
  File "mechanize/_opener.py", line 193, in open
  File "mechanize/_urllib2_fork.py", line 425, in _open
  File "mechanize/_urllib2_fork.py", line 414, in _call_chain
  File "mechanize/_urllib2_fork.py", line 1283, in https_open
  File "mechanize/_urllib2_fork.py", line 1240, in do_open
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:997)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 55, in _translate_text
    return self.translator.translate(text)
  File "calibre_plugins.ebook_translator.engines.chatgpt", line 88, in translate
    return self.get_result(
  File "calibre_plugins.ebook_translator.engines.base", line 179, in get_result
    raise Exception(
Exception: Can not parse returned response. Raw data: <urlopen error EOF occurred in violation of protocol (_ssl.c:997)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mechanize/_urllib2_fork.py", line 1236, in do_open
  File "http/client.py", line 1282, in request
  File "http/client.py", line 1328, in _send_request
  File "http/client.py", line 1277, in endheaders
  File "http/client.py", line 1037, in _send_output
  File "http/client.py", line 975, in send
  File "http/client.py", line 1454, in connect
  File "ssl.py", line 512, in wrap_socket
  File "ssl.py", line 1070, in _create
  File "ssl.py", line 1341, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 167, in get_result
    self.br.open(request)
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 287, in _mech_open
  File "mechanize/_opener.py", line 193, in open
  File "mechanize/_urllib2_fork.py", line 425, in _open
  File "mechanize/_urllib2_fork.py", line 414, in _call_chain
  File "mechanize/_urllib2_fork.py", line 1283, in https_open
  File "mechanize/_urllib2_fork.py", line 1240, in do_open
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:997)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 55, in _translate_text
    return self.translator.translate(text)
  File "calibre_plugins.ebook_translator.engines.chatgpt", line 88, in translate
    return self.get_result(
  File "calibre_plugins.ebook_translator.engines.base", line 179, in get_result
    raise Exception(
Exception: Can not parse returned response. Raw data: <urlopen error EOF occurred in violation of protocol (_ssl.c:997)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.advanced", line 159, in translate_paragraphs
    translation.handle(paragraphs)
  File "calibre_plugins.ebook_translator.translation", line 149, in handle
    async_request.run()
  File "calibre_plugins.ebook_translator.request", line 37, in run
    asyncio.run(self.create_tasks())
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 641, in run_until_complete
  File "calibre_plugins.ebook_translator.request", line 34, in create_tasks
    await asyncio.gather(*self.tasks)
  File "calibre_plugins.ebook_translator.request", line 22, in create_worker
    self.process_translation(paragraph)
  File "calibre_plugins.ebook_translator.translation", line 144, in process_translation
    self._prepare_translation(paragraph)
  File "calibre_plugins.ebook_translator.translation", line 102, in _prepare_translation
    translation = self._translate_text(original)
  File "calibre_plugins.ebook_translator.translation", line 88, in _translate_text
    return self._translate_text(text, count, interval)
  File "calibre_plugins.ebook_translator.translation", line 88, in _translate_text
    return self._translate_text(text, count, interval)
  File "calibre_plugins.ebook_translator.translation", line 88, in _translate_text
    return self._translate_text(text, count, interval)
  File "calibre_plugins.ebook_translator.translation", line 78, in _translate_text
    raise Exception('{} {}'.format(message, str(e)))
Exception: Failed to retreive data from translate engine API. Can not parse returned response. Raw data: <urlopen error EOF occurred in violation of protocol (_ssl.c:997)>
```

**Comment by bookfere** [comment]
看起来这是个网络问题。你使用网络代理了吗？如果有的话更换 IP 或代理试试。
